### PR TITLE
Fix resources fetching twice

### LINKED ISSUE #233: Resources fetching twice initially
I've noticed in certain cases resources fetching twice on the initial load. @psealock has also noticed this in the wc-admin PR: https://github.com/woocommerce/woocommerce-admin/pull/2737

### PR DESCRIPTION
**Pull request by coderkevin**
Fixes #233 

This fixes the problem where resources were getting fetched twice
because of the way react-redux connect works with rendering components
and sending out redux store subscriptions.

Disclaimer: This fix is a bit hacky to get around an issue we're having with redux where reducers are processed before subscribers to the redux store. I've been thinking of removing redux completely from fresh-data as a dependency and this is pushing me more in that direction.

To Test:
1. `npm install`
2. `npm run bootstrap`
3. `npm run build`
4. `rm -rf packages/react-provider/node_modules/react-redux` (necessary because of local linking issues)
5. `cd examples/wp-rest-api`
6. `npm start`

After this, you should be able to observe only one initial fetch instead of two when using the code on master. (pro-tip: in the JS console run `localStorage.setItem( 'debug', 'fresh-data:*' );` to see debug messages.

### CODE REVIEW

File: packages/framework/src/client/index.js [hunk 1]
```diff
@@ -84,7 +94,13 @@ export default class ApiClient {
 	requireResource = ( requirement, resourceName, now = new Date() ) => {
 		const resources = this.state.resources || {};
 		const resourceState = resources[ resourceName ] || {};
-		this.scheduler.scheduleRequest( requirement, resourceState, resourceName, this.readOperationName, undefined, now );
+		// TODO: Remove this check after redux state is simplified out.
+		// This is necessary because components are getting re-rendered twice when dataReceived is dispatched.
+		// First before the state is updated, and second afterwards. This prevents resources from getting rescheduled
+		// on the first re-render. After redux dispatching is no longer used, components should no longer re-render twice.
+		if ( ! this.isStateStale ) {
```
Comment (reykjalin) [inline packages/framework/src/client/index.js]: Minor nitpick in regards to variable names:

I feel like the request should be scheduled when the state is stale? I feel like when the state is "fresh" (i.e. not stale) there is no need to update, therefore no need to schedule?

Writing this out I see another contradiction here: why wouldn't you be able to schedule a request when the state is stale?

I understand that this is all stale vs. fresh in the context of this specific issue, but it feels like it can be easily be confused to represent something in the greater context of the system as a whole.
Am I reading too much into this (or misunderstanding the variable name?) or would it be better to choose a better name? Maybe `shouldScheduleRequest` or something along those lines?

Comment (coderkevin) [reply packages/framework/src/client/index.js]: Yeah, maybe stale isn't correct and is overloaded in a module called "fresh-data" 😄 

Granted, this is temporary code, but even so I could change it to `isClientStateInSync` maybe, to show that the client object's state is either in sync or out of sync with the greater redux state?

Comment (reykjalin) [reply packages/framework/src/client/index.js]: Yeah, that sounds better already! I might even go so far as to add a comment _somewhere_ explaining what this variable is _really_ about simply because I think it's hard to convey with a name 🤔 

I'll leave that up to you though, with the reminder that "temporary" code often turns out to be not-so-temporary 😃

Comment (coderkevin) [reply packages/framework/src/client/index.js]: Resolved in 542c009
